CREATE TABLE IF NOT EXISTS INVENTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    PACK_TYPE VARCHAR(50) NOT NULL,
    QUANTITY INT NOT NULL,
    STATE VARCHAR(50) NOT NULL
);
