CREATE TABLE IF NOT EXISTS INWARD_ORDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CHANNEL_ORDER_ID VARCHAR(255) NOT NULL,
    CHANNEL VARCHAR(50) NOT NULL,
    TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    WAREHOUSE_ID BIGINT,
    CONSTRAINT UC_CHANNEL_ORDER_ID UNIQUE (CHANNEL, CHANNEL_ORDER_ID)
);

CREATE TABLE IF NOT EXISTS INWARD_ORDER_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    ORDERED_QUANTITY INT NOT NULL,
    RECEIVED_QUANTITY INT NOT NULL
);

CREATE TABLE IF NOT EXISTS GATE_ENTRIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS GATE_ENTRY_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    GATE_ENTRY_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL
);

CREATE TABLE IF NOT EXISTS OUTWARD_ORDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CHANNEL_ORDER_ID VARCHAR(255) NOT NULL,
    CHANNEL VARCHAR(50) NOT NULL,
    WAREHOUSE_ID BIGINT,
    TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CONSTRAINT UC_OUTWARD_CHANNEL_ORDER_ID UNIQUE (CHANNEL, CHANNEL_ORDER_ID)
);

CREATE TABLE IF NOT EXISTS OUTWARD_ORDER_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    ORDERED_QUANTITY INT NOT NULL,
    ALLOCATED_QUANTITY INT NOT NULL
);

CREATE TABLE IF NOT EXISTS WAREHOUSES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(50) NOT NULL UNIQUE,
    TYPE VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(500)
);
