CREATE TABLE IF NOT EXISTS GATE_ENTRIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INWARD_ORDER_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS STORAGE_BOXES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    GATE_ENTRY_ID BIGINT,
    LOCATION_ID BIGINT,
    WAREHOUSE_ID BIGINT
);

CREATE TABLE IF NOT EXISTS ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    WAREHOUSE_ID BIGINT
);

CREATE TABLE IF NOT EXISTS BOX_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID BIGINT NOT NULL,
    BOX_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AISLE VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL,
    WAREHOUSE_ID BIGINT
);

CREATE TABLE IF NOT EXISTS WM_OUTWARD_ORDERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_MANAGEMENT_ID BIGINT,
    CHANNEL_ORDER_ID VARCHAR(255) NOT NULL,
    CHANNEL VARCHAR(50) NOT NULL,
    WAREHOUSE_ID BIGINT,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS WM_OUTWARD_ORDER_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    PICK_LIST_COUNT INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS PICK_LISTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    STORAGE_BOX_ID BIGINT NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);
