CREATE TABLE IF NOT EXISTS GATE_ENTRIES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    INWARD_ORDER_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS STORAGE_BOXES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL,
    GATE_ENTRY_ID BIGINT,
    LOCATION_ID BIGINT
);

CREATE TABLE IF NOT EXISTS ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID BIGINT NOT NULL,
    STATUS VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS BOX_ITEMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ITEM_ID BIGINT NOT NULL,
    BOX_ID BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCATIONS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    AISLE VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(255) NOT NULL
);
